# Database Configuration - I'll use H2 for that example.
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enable: true
      path: /h2-console
#JPA
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# GraphQL
#graphql:
#  servlet:
#    mapping: /apis/graphql